[package]
name = "job_marketplace_v29"
version = "1.0.0"
authors = []
license = "MIT"

[addresses]
job_work_board = "0x5de1dd560f3136745d46807f1b3e599077966a3b1d87047faef143a71c39d511" 
did_addr_profile = "0x5de1dd560f3136745d46807f1b3e599077966a3b1d87047faef143a71c39d511"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-stdlib" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/move-stdlib" }

[dev-addresses]
