[package]
name = "did_project"
version = "1.0.0"

[addresses]
work_profiles_addr = "0x2be9b4c599f0233833c893e16241f4ba5a040916258c49f50d6d94ceaf236b48" 

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-addresses]
